### ISSUE TITLE
Running create-code-mod-app crashes on Windows

### ISSUE THREAD

**Issue by blaster151** [dangreenisrael/create-codemod-app#19]
Love this idea, looks like an awesome project!  I'm getting the following error whether I run using `npx` or install create-codemod-app globally.  I tried from elevated-permission "command line", "git bash", and Powershell windows just in case.  Right after prompting for the name of the new codemod app, this happens.  The new directory does not get created which explains why the attempt to `cd` into it appears to fail.

I am still finding use just from one-offing the example-codemod-app folder alone, but I'd love to figure out what this issue is so I can use the project as intended.  (Is it relying on the fs-event package, which doesn't function on Windows?  Just speculating.)

````
Setting up the app and running `npm install`

The system cannot find the path specified.
(node:3292) UnhandledPromiseRejectionWarning: Error: Command failed: cd xxx; npm install
    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at run (C:\ProgramData\nvm\v12.16.1\node_modules\create-codemod-app\bin\create-codemod-app.js:58:3)
(node:3292) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3292) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
````

**Comment by dangreenisrael** [comment]
Hi, unfortunately I have no access to Windows. If you would like to open a PR I'd be happy to take a look at it - but I can't make any promises on a time frame. Sorry.

**Comment by dangreenisrael** [comment]
> Error: Command failed: cd xxx; npm install

**Comment by dangreenisrael** [comment]
Closing as no response from the OP
